PG_DB_NAME="postgres"
PG_DB_USER="postgres.zbxqskgqoqodgaltyqix"
PG_DB_PASSWORD="*vePzzMUnt9-Fz@"
PG_DB_HOST="aws-0-eu-central-1.pooler.supabase.com"
PG_DB_PORT="6543"

# Auch das Admin-Passwort für die Streamlit-App hier speichern
HANDBALL_ADMIN_PASSWORD="handball_admin_123"
